on:
  pull_request:
    types : [open]
  push:
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Send a dispatch POST event
      uses: fjogeleit/http-request-action@v1.9.2

      with:
        url: "https://api.github.com/repos/akshaygupta-dev/ubuntu-nginx-server/dispatches"
        method: "POST"
        customHeaders: '{"Accept": "application/vnd.github.v3+json", "Authorization": "token ${{ secrets.SECRET_KEY }}"}'
        data:  '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'
  
